import type { IconifyJSON } from "@iconify/svelte/dist/functions";

import iconData from "$lib/icons/generated/iconData.json";

// The committed offline icon-data bundle (generated by scripts/generate-icons.mjs):
// one per-prefix IconifyJSON subset covering the map's pin vocabulary and the
// app's <Icon> usages. A single source of icon data, consumed two ways —
// renderBundledIcon bakes pin/badge sprites from it, and registerOfflineIcons
// hands it to @iconify/svelte's addCollection for the <Icon> component.
export const iconCollections = iconData as Record<string, IconifyJSON>;
