export type SocialIconName =
	| 'amboss'
	| 'discord'
	| 'email'
	| 'facebook'
	| 'github'
	| 'instagram'
	| 'linkedin'
	| 'matrix'
	| 'nostr'
	| 'reddit'
	| 'signal'
	| 'telegram'
	| 'website'
	| 'whatsapp'
	| 'x'
	| 'youtube';

export type AppIconName = 'android' | 'f-droid' | 'ios' | 'play' | 'web';

export type MobileNavIconName =
	| 'activity'
	| 'add'
	| 'api'
	| 'apps'
	| 'areas-highlight'
	| 'areas'
	| 'bars'
	| 'close'
	| 'communities'
	| 'contribute-highlight'
	| 'contribute'
	| 'countries'
	| 'dash'
	| 'directory'
	| 'general'
	| 'issue'
	| 'leader'
	| 'map-highlight'
	| 'map'
	| 'stats-highlight'
	| 'stats'
	| 'support'
	| 'ticket'
	| 'verify'
	| 'wiki-highlight'
	| 'wiki';
