import { get, writable } from "svelte/store";
import { beforeEach, describe, expect, it, vi } from "vitest";

import api from "$lib/axios";
import type { Session } from "$lib/session";

vi.mock("$lib/axios", () => ({
	default: { get: vi.fn() },
}));

type ApiMock = { get: ReturnType<typeof vi.fn> };

function makeSession(overrides: Partial<Session> = {}): Session {
	return {
		username: "alice",
		password: "",
		token: "tok",
		savedPlaces: [1, 2],
		savedAreas: [],
		autoGenerated: true,
		...overrides,
	};
}

function setVisibility(state: "visible" | "hidden") {
	Object.defineProperty(document, "visibilityState", {
		value: state,
		configurable: true,
	});
	document.dispatchEvent(new Event("visibilitychange"));
}

// Drain pending microtasks without advancing fake timers — the initial poll
// is kicked off synchronously from subscribe(), so we only need the inFlight
// promise chain to resolve before assertions run.
async function flushMicrotasks() {
	for (let i = 0; i < 5; i++) await Promise.resolve();
}

async function freshModule() {
	vi.resetModules();
	return await import("$lib/activityNotifier");
}

describe("activityNotifier — pure helpers and stores", () => {
	beforeEach(() => {
		localStorage.clear();
		vi.restoreAllMocks();
	});

	it("storageKeyFor returns a per-username key", async () => {
		const m = await freshModule();
		expect(m.storageKeyFor("alice")).toBe("btcmap_activity_lastseen:alice");
	});

	it("hasNewActivity is false when latest is null", async () => {
		const m = await freshModule();
		expect(get(m.hasNewActivity)).toBe(false);
	});

	it("hasNewActivity is true when latest > lastSeen", async () => {
		const m = await freshModule();
		m.latestActivityDate.set("2026-05-06T10:00:00Z");
		m.lastSeenActivityDate.set("2026-05-06T09:00:00Z");
		expect(get(m.hasNewActivity)).toBe(true);
	});

	it("hasNewActivity is false when latest equals lastSeen", async () => {
		const m = await freshModule();
		m.latestActivityDate.set("2026-05-06T10:00:00Z");
		m.lastSeenActivityDate.set("2026-05-06T10:00:00Z");
		expect(get(m.hasNewActivity)).toBe(false);
	});

	it("hasNewActivity is true when lastSeen is null but latest is set", async () => {
		const m = await freshModule();
		m.latestActivityDate.set("2026-05-06T10:00:00Z");
		m.lastSeenActivityDate.set(null);
		expect(get(m.hasNewActivity)).toBe(true);
	});

	it("markActivitySeen writes the per-username key and updates the store", async () => {
		const m = await freshModule();
		m.markActivitySeen("alice", "2026-05-06T10:00:00Z");
		expect(localStorage.getItem("btcmap_activity_lastseen:alice")).toBe(
			"2026-05-06T10:00:00Z",
		);
		expect(get(m.lastSeenActivityDate)).toBe("2026-05-06T10:00:00Z");
	});

	it("loadLastSeen reads the per-username key into the store", async () => {
		localStorage.setItem(
			"btcmap_activity_lastseen:alice",
			"2026-05-06T08:00:00Z",
		);
		const m = await freshModule();
		m.loadLastSeen("alice");
		expect(get(m.lastSeenActivityDate)).toBe("2026-05-06T08:00:00Z");
	});

	it("loadLastSeen sets store to null when no key exists", async () => {
		const m = await freshModule();
		m.lastSeenActivityDate.set("stale");
		m.loadLastSeen("alice");
		expect(get(m.lastSeenActivityDate)).toBeNull();
	});
});

describe("activityNotifier — polling", () => {
	beforeEach(() => {
		localStorage.clear();
		vi.useFakeTimers();
		vi.restoreAllMocks();
		(api as unknown as ApiMock).get = vi.fn();
		setVisibility("visible");
	});

	it("does not fetch when session is null", async () => {
		const m = await freshModule();
		const sessionStore = writable<Session | null>(null);
		const stop = m.startActivityPolling(sessionStore);
		await Promise.resolve();
		expect((api as unknown as ApiMock).get).not.toHaveBeenCalled();
		stop();
	});

	it("does not fetch when session has no saved items", async () => {
		const m = await freshModule();
		const sessionStore = writable<Session | null>(
			makeSession({ savedPlaces: [], savedAreas: [] }),
		);
		const stop = m.startActivityPolling(sessionStore);
		await Promise.resolve();
		expect((api as unknown as ApiMock).get).not.toHaveBeenCalled();
		stop();
	});

	it("fetches once on start when session has saved places", async () => {
		(api as unknown as ApiMock).get.mockResolvedValue({
			data: [
				{ type: "place_added", place_id: 1, date: "2026-05-06T10:00:00Z" },
			],
		});
		const m = await freshModule();
		const sessionStore = writable<Session | null>(makeSession());
		const stop = m.startActivityPolling(sessionStore);
		await flushMicrotasks();
		expect((api as unknown as ApiMock).get).toHaveBeenCalledTimes(1);
		const url = (api as unknown as ApiMock).get.mock.calls[0][0] as string;
		expect(url).toContain("/v4/activity?");
		expect(url).toContain("days=1");
		expect(url).toContain("places=1%2C2");
		stop();
	});

	it("bootstraps lastSeen on first poll so no dot appears initially", async () => {
		(api as unknown as ApiMock).get.mockResolvedValue({
			data: [
				{ type: "place_added", place_id: 1, date: "2026-05-06T10:00:00Z" },
			],
		});
		const m = await freshModule();
		const sessionStore = writable<Session | null>(makeSession());
		const stop = m.startActivityPolling(sessionStore);
		await flushMicrotasks();
		expect(localStorage.getItem("btcmap_activity_lastseen:alice")).toBe(
			"2026-05-06T10:00:00Z",
		);
		expect(get(m.hasNewActivity)).toBe(false);
		stop();
	});

	it("shows hasNewActivity=true on a second poll with newer data", async () => {
		const apiMock = (api as unknown as ApiMock).get;
		apiMock
			.mockResolvedValueOnce({
				data: [
					{ type: "place_added", place_id: 1, date: "2026-05-06T10:00:00Z" },
				],
			})
			.mockResolvedValueOnce({
				data: [
					{ type: "place_added", place_id: 1, date: "2026-05-06T11:00:00Z" },
				],
			});
		const m = await freshModule();
		const sessionStore = writable<Session | null>(makeSession());
		const stop = m.startActivityPolling(sessionStore);
		await flushMicrotasks();
		await vi.advanceTimersByTimeAsync(m.POLL_INTERVAL_MS);
		await Promise.resolve();
		expect(get(m.latestActivityDate)).toBe("2026-05-06T11:00:00Z");
		expect(get(m.hasNewActivity)).toBe(true);
		stop();
	});

	it("does not poll while document is hidden", async () => {
		(api as unknown as ApiMock).get.mockResolvedValue({ data: [] });
		const m = await freshModule();
		const sessionStore = writable<Session | null>(makeSession());
		setVisibility("hidden");
		const stop = m.startActivityPolling(sessionStore);
		await vi.advanceTimersByTimeAsync(m.POLL_INTERVAL_MS * 2);
		expect((api as unknown as ApiMock).get).not.toHaveBeenCalled();
		stop();
	});

	it("re-fetches on visibilitychange when interval elapsed while hidden", async () => {
		(api as unknown as ApiMock).get.mockResolvedValue({ data: [] });
		const m = await freshModule();
		const sessionStore = writable<Session | null>(makeSession());
		const stop = m.startActivityPolling(sessionStore);
		await flushMicrotasks();
		expect((api as unknown as ApiMock).get).toHaveBeenCalledTimes(1);

		setVisibility("hidden");
		await vi.advanceTimersByTimeAsync(m.POLL_INTERVAL_MS + 1000);
		setVisibility("visible");
		await Promise.resolve();
		expect((api as unknown as ApiMock).get).toHaveBeenCalledTimes(2);
		stop();
	});

	it("stop() halts further polls", async () => {
		(api as unknown as ApiMock).get.mockResolvedValue({ data: [] });
		const m = await freshModule();
		const sessionStore = writable<Session | null>(makeSession());
		const stop = m.startActivityPolling(sessionStore);
		await flushMicrotasks();
		stop();
		await vi.advanceTimersByTimeAsync(m.POLL_INTERVAL_MS * 3);
		expect((api as unknown as ApiMock).get).toHaveBeenCalledTimes(1);
	});

	it("starts polling when saved items appear mid-session (same username)", async () => {
		(api as unknown as ApiMock).get.mockResolvedValue({
			data: [
				{ type: "place_added", place_id: 1, date: "2026-05-06T10:00:00Z" },
			],
		});
		const m = await freshModule();
		// User signs in with zero saved items — no polling yet.
		const sessionStore = writable<Session | null>(
			makeSession({ savedPlaces: [], savedAreas: [] }),
		);
		const stop = m.startActivityPolling(sessionStore);
		await flushMicrotasks();
		expect((api as unknown as ApiMock).get).not.toHaveBeenCalled();

		// User saves their first place — same username, savedPlaces grows.
		sessionStore.set(makeSession({ savedPlaces: [1] }));
		await flushMicrotasks();
		expect((api as unknown as ApiMock).get).toHaveBeenCalledTimes(1);
		stop();
	});

	it("stops polling when the user unsaves their last item", async () => {
		(api as unknown as ApiMock).get.mockResolvedValue({ data: [] });
		const m = await freshModule();
		const sessionStore = writable<Session | null>(makeSession());
		const stop = m.startActivityPolling(sessionStore);
		await flushMicrotasks();
		expect((api as unknown as ApiMock).get).toHaveBeenCalledTimes(1);

		// User unsaves their last item — interval should clear so we don't
		// keep polling for nothing.
		sessionStore.set(makeSession({ savedPlaces: [], savedAreas: [] }));
		await flushMicrotasks();
		await vi.advanceTimersByTimeAsync(m.POLL_INTERVAL_MS * 2);
		expect((api as unknown as ApiMock).get).toHaveBeenCalledTimes(1);
		stop();
	});

	it("logout (session → null) clears stores and stops polling", async () => {
		(api as unknown as ApiMock).get.mockResolvedValue({
			data: [
				{ type: "place_added", place_id: 1, date: "2026-05-06T10:00:00Z" },
			],
		});
		const m = await freshModule();
		const sessionStore = writable<Session | null>(makeSession());
		const stop = m.startActivityPolling(sessionStore);
		await flushMicrotasks();
		sessionStore.set(null);
		await Promise.resolve();
		expect(get(m.latestActivityDate)).toBeNull();
		expect(get(m.lastSeenActivityDate)).toBeNull();
		await vi.advanceTimersByTimeAsync(m.POLL_INTERVAL_MS * 2);
		expect((api as unknown as ApiMock).get).toHaveBeenCalledTimes(1);
		stop();
	});
});
