// This file is generated by icon spritesheet generator

export const iconNames = [
  "wiki",
  "wiki-highlight",
  "verify",
  "ticket",
  "support",
  "stats",
  "stats-highlight",
  "map",
  "map-highlight",
  "leader",
  "issue",
  "general",
  "directory",
  "dash",
  "countries",
  "contribute",
  "contribute-highlight",
  "communities",
  "close",
  "bars",
  "areas",
  "areas-highlight",
  "apps",
  "api",
  "add",
  "activity",
] as const

export type IconName = typeof iconNames[number]
