// This file is generated by icon spritesheet generator

export const iconNames = [
  "youtube",
  "x",
  "whatsapp",
  "website",
  "telegram",
  "signal",
  "reddit",
  "nostr",
  "linkedin",
  "instagram",
  "github",
  "facebook",
  "email",
  "discord",
  "amboss",
] as const

export type IconName = typeof iconNames[number]
