// This file is generated by icon spritesheet generator

export const iconNames = [
  "verified",
  "twitter",
  "tags",
  "share",
  "phone",
  "pencil",
  "outdated",
  "issues",
  "instagram",
  "info-circle",
  "globe",
  "facebook",
  "external",
  "email",
  "dots-horizontal",
  "compass",
  "clock",
  "boosted-icon-pin",
  "boost",
  "boost-solid",
  "bolt",
] as const

export type IconName = typeof iconNames[number]
