version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'typescript-eslint'
      prettier:
        patterns:
          - '*prettier*'
