version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      biome:
        patterns:
          - '@biomejs/*'
      svelte:
        patterns:
          - 'svelte'
          - '@sveltejs/*'
          - 'svelte-*'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      playwright:
        patterns:
          - '@playwright/*'
      leaflet:
        patterns:
          - 'leaflet'
          - 'leaflet.*'
          - '@maplibre/*'
          - 'maplibre-gl'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
