// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";

export type AreaSearchResult = { id: number, name: string, type: string, url_alias: string, icon: string | null, website_url: string, upcoming_events: Array<Event>, };
