// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AreaReportTags = { total_elements: number, total_elements_onchain: number, total_elements_lightning: number, total_elements_lightning_contactless: number, total_atms: number, total_merchants: number, total_exchanges: number, up_to_date_elements: number, up_to_date_percent: number, outdated_elements: number, legacy_elements: number, 
/**
 * Average verification date across the area's places, as stored. Omitted
 * when the row predates the field or no place had a verification date.
 */
avg_verification_date?: string, };
