// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AreaSearchResult = { id: number, name: string, type: string, url_alias: string, icon: string | null, website_url: string, };
