// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Delta sync payload. Every field except `id` is optional and omitted unless
 * the caller asked for it in `fields`, so a client only pays for the columns
 * it stores. Raw tags are never exposed; geometry is available through `bbox`
 * (compact, for map placement) and `geo_json` (the full polygon, only sent
 * when explicitly requested because it can be large).
 */
export type AreaDelta = { id: number, name?: string, type?: string, url_alias?: string, icon?: string, icon_wide?: string, website_url?: string, description?: string, 
/**
 * Every `name:<lang>` tag whose language suffix is exactly two characters,
 * keyed by that code. Lets an offline client pick the right name itself
 * instead of paying for a round trip per language. The singular `name`
 * above stays the base tag unless `lang` is passed.
 */
localized_name?: Record<string, string>, 
/**
 * Every `description:<lang>` tag whose language suffix is exactly two
 * characters, keyed by that code. Mirrors `localized_name`.
 */
localized_description?: Record<string, string>, 
/**
 * `[west, south, east, north]`. Omitted when the area has no bbox of its
 * own, i.e. the stored columns still hold the whole-world default.
 */
bbox?: [number, number, number, number], 
/**
 * Full GeoJSON geometry exactly as stored in the area's tags. Only sent
 * when explicitly requested via `fields` because polygons can be large.
 */
geo_json?: Record<string, unknown>, created_at?: string, updated_at?: string, deleted_at?: string, };
