// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AreaReportTags } from "./AreaReportTags";

export type AreaReport = { id: number, date: string, tags: AreaReportTags, created_at: string, updated_at: string, };
