// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangeEventStatusArgs = { 
/**
 * Target status. Only `live` and `rejected` are valid here; events are
 * created as `pending` and never return to it through this endpoint.
 */
status: string, };
