// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeResponse } from "./MeResponse";

export type CreateTokenResponse = { token: string, user: MeResponse, };
