// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartEntry } from "./ChartEntry";

export type Dashboard = { total_merchants: number, total_merchants_chart: Array<ChartEntry>, verified_merchants_1y: number, verified_merchants_1y_chart: Array<ChartEntry>, total_exchanges: number, total_exchanges_chart: Array<ChartEntry>, verified_exchanges_1y: number, total_areas: number, verified_areas_1y: number, };
