// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Event = { id: number, lat: number, lon: number, name: string, website: string, starts_at: string, ends_at?: string, updated_at?: string, deleted_at?: string, };
