// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Submitter of an event, exposed as a nested `submitted_by` object on every
 * v4 event response.
 */
export type EventAuthor = { id: number, name: string, };
