// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedArea } from "./SavedArea";
import type { SavedPlace } from "./SavedPlace";

export type MeResponse = { id: number, name: string, roles: Array<string>, saved_places: Array<SavedPlace>, saved_areas: Array<SavedArea>, 
/**
 * Bech32 npub (`npub1...`) of the Nostr identity linked to this user,
 * or `null` when no pubkey is linked.
 */
npub: string | null, };
