// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NostrIdentityResponse = { 
/**
 * Bech32 npub (`npub1...`) currently linked to the account, or `null`.
 */
npub: string | null, };
