// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaceSubmission = { id: number, origin: string, external_id: string, lat: number, lon: number, category: string, name: string, extra_fields: Record<string, unknown>, ticket_url: string | null, revoked: boolean, submitted_by?: number, created_at: string, updated_at: string, closed_at?: string, deleted_at?: string, };
