// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type-export-only description of the dynamic place responses.
 * `GET /v4/places` and `GET /v4/places/{id}` build their JSON at runtime
 * from the `fields` query param, so every field except `id` is optional.
 * Fields requested via the `osm:<tag>` passthrough appear as extra keys and
 * cannot be typed statically. Kept in sync with `service::element::TAGS` by
 * `place_type_covers_all_generate_tags_fields`.
 */
export type Place = { id: number, osm_id?: string, osm_url?: string, osm_edit_url?: string, lat?: number, lon?: number, name?: string, address?: string, icon?: string, phone?: string, website?: string, twitter?: string, facebook?: string, instagram?: string, line?: string, email?: string, opening_hours?: string, boosted_until?: string, required_app_url?: string, created_at?: string, updated_at?: string, deleted_at?: string, verified_at?: string, comments?: number, description?: string, image?: string, payment_provider?: string, telegram?: string, localized_name?: Record<string, string>, localized_opening_hours?: Record<string, string>, };
