// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceIssueSummary } from "./PlaceIssueSummary";

export type PlaceIssuesRes = { total_issues: number, requested_issues: Array<PlaceIssueSummary>, };
