// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaceImage = { id: number, place_id: number, type: string, width: number, height: number, size_bytes: number, created_at: string, created_by?: number, };
