// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uploader of a place image, exposed as a nested `author` object so clients
 * can migrate off the top-level `created_by` id (which is kept for backwards
 * compatibility).
 */
export type PlaceImageAuthor = { id: number, name: string, };
