// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostPlaceReportArgs = { place_id: number, type: string, extra_fields: Record<string, unknown>, };
