// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostPlaceReportPhotoArgs } from "./PostPlaceReportPhotoArgs";

export type PostPlaceReportArgs = { place_id: number, type: string, extra_fields: Record<string, unknown>, photos?: Array<PostPlaceReportPhotoArgs>, };
