// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostEventArgs = { lat: number, lon: number, name: string, website: string, 
/**
 * RFC 3339 with an offset, or a floating local datetime that needs
 * `timezone` to be placed on the timeline.
 */
starts_at: string, ends_at?: string, 
/**
 * Either `"auto"` (infer from lat/lon) or an IANA zone name.
 */
timezone: string | null, area_id: number | null, };
