// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationInfo } from "./PaginationInfo";
import type { SearchResult } from "./SearchResult";

export type SearchResponse = { results: Array<SearchResult>, total_count: number, has_more: boolean, query: string, pagination: PaginationInfo, };
