// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchedArea = { id: number, name: string, alias?: string, 
/**
 * `[west, south, east, north]`. Absent when the area has no bbox of its own.
 */
bbox?: [number, number, number, number], 
/**
 * `icon:square` from the area's tags. Absent when the area has no icon.
 */
icon?: string, };
