// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { SearchedArea } from "./SearchedArea";
import type { SearchedPlace } from "./SearchedPlace";

/**
 * `SearchedPlace` is boxed because it is an order of magnitude larger than
 * `SearchedArea`, and clippy's `large_enum_variant` would otherwise fire. The
 * event variant reuses the `/v4/events` item so both endpoints return the same
 * object.
 */
export type SearchResult = { "type": "area" } & SearchedArea | { "type": "place" } & SearchedPlace | { "type": "event" } & Event;
