// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignoutResponse = { id: number, label: string | null, revoked_at?: string, };
