<script lang="ts">
import OutClick from "svelte-outclick";

import BackupModal from "$components/auth/BackupModal.svelte";
import Icon from "$components/Icon.svelte";
import { _ } from "$lib/i18n";
import { session } from "$lib/session";

import { afterNavigate } from "$app/navigation";

let open = false;
let showBackup = false;
const triggerId = `user-menu-trigger-${Math.random().toString(36).slice(2, 8)}`;

afterNavigate(() => {
	open = false;
});
</script>

<div class="relative">
	<button
		id={triggerId}
		on:click={() => (open = !open)}
		class="flex h-10 w-10 items-center justify-center text-white transition-opacity hover:opacity-80"
		aria-label={$session?.username ?? $_("nav.account")}
		title={$session?.username ?? $_("nav.account")}
		aria-haspopup="true"
		aria-expanded={open}
	>
		<Icon
			type="material"
			icon={$session ? 'account_circle_filled' : 'account_circle'}
			w="24"
			h="24"
		/>
	</button>

	{#if open}
		<OutClick
			excludeQuerySelectorAll={`#${triggerId}`}
			on:outclick={() => (open = false)}
		>
			<div
				class="absolute right-0 top-full z-50 mt-2 w-48 rounded-lg border border-gray-300 bg-white py-1 shadow-lg dark:border-white/20 dark:bg-dark"
			>
				{#if $session}
					<a
						href="/saved"
						class="flex items-center gap-2 px-4 py-2 text-sm text-primary transition-colors hover:bg-gray-100 dark:text-white dark:hover:bg-white/10"
					>
						<Icon type="material" icon="bookmark" w="16" h="16" />
						{$_("nav.mySaved")}
					</a>

					{#if $session.autoGenerated}
						<button
							on:click={() => {
								open = false;
								showBackup = true;
							}}
							class="flex w-full items-center gap-2 px-4 py-2 text-sm text-primary transition-colors hover:bg-gray-100 dark:text-white dark:hover:bg-white/10"
						>
							<Icon type="material" icon="key" w="16" h="16" />
							{$_("nav.backupAccount")}
						</button>
					{/if}

					<hr class="my-1 border-gray-200 dark:border-white/10" />

					<button
						on:click={() => {
							session.clear();
							open = false;
						}}
						class="flex w-full items-center gap-2 px-4 py-2 text-sm text-primary transition-colors hover:bg-gray-100 dark:text-white dark:hover:bg-white/10"
					>
						<Icon type="material" icon="logout" w="16" h="16" />
						{$_("nav.logout")}
					</button>
				{:else}
					<a
						href="/login"
						class="flex items-center gap-2 px-4 py-2 text-sm text-primary transition-colors hover:bg-gray-100 dark:text-white dark:hover:bg-white/10"
					>
						<Icon type="material" icon="login" w="16" h="16" />
						{$_("nav.login")}
					</a>
				{/if}
			</div>
		</OutClick>
	{/if}
</div>

{#if showBackup}
	<BackupModal on:close={() => (showBackup = false)} />
{/if}
