<script lang="ts">
import type { VerifiedEvent } from "nostr-tools/pure";
import { onMount } from "svelte";
import { get } from "svelte/store";

import api from "$lib/axios";
import { _ } from "$lib/i18n";
import {
	decodeNsec,
	getNostrExtension,
	signAuthWithExtension,
	signAuthWithSecretKey,
} from "$lib/nostr";
import type { Session } from "$lib/session";
import { session } from "$lib/session";
import { errToast } from "$lib/utils";

// Mirrors LoginForm's contract: caller decides what happens after a
// successful login (navigate, complete a pending save, etc.).
export let onSuccess: (session: Session) => void | Promise<void>;

let hasNostrExtension = false;
let showNsecInput = false;
let nsec = "";
let nostrLoading = false;
let nsecLoading = false;

onMount(() => {
	// Extensions inject window.nostr before page load, but a few are slow.
	// One re-check after a short delay covers the late-injection case
	// without blocking first paint when no extension is present.
	hasNostrExtension = getNostrExtension() !== null;
	if (hasNostrExtension) return;
	const t = setTimeout(() => {
		hasNostrExtension = getNostrExtension() !== null;
	}, 300);
	return () => clearTimeout(t);
});

async function exchangeSignedEvent(signedEvent: VerifiedEvent) {
	const res = await api.post("/api/session/nostr", {
		signed_event: signedEvent,
	});

	const token = res.data?.token;
	const apiUsername = res.data?.username;
	if (typeof token !== "string" || typeof apiUsername !== "string") {
		throw new Error("Nostr auth did not return a token");
	}

	// Empty password — Nostr-linked accounts back up via the Nostr key,
	// not via a stored password. autoGenerated stays false (set by
	// session.login), so BackupModal won't show a password field.
	session.login(apiUsername, "", token);

	const current = get(session);
	if (!current) throw new Error("session.login did not populate the store");

	await onSuccess(current);
}

async function loginWithExtension() {
	// Re-entry guard: the disabled prop on the button propagates async, so
	// a second click (or Enter on a focused button) can fire this handler
	// before disabled takes effect. Without the guard, the user would see
	// two extension-signing popups for one click.
	if (nostrLoading) return;
	nostrLoading = true;
	try {
		const signed = await signAuthWithExtension();
		await exchangeSignedEvent(signed);
	} catch (err) {
		const status = (err as { response?: { status?: number } })?.response
			?.status;
		errToast(status === 401 ? $_("login.nostrFailed") : $_("login.nostrError"));
		console.error("Nostr extension login failed:", status ?? "unknown");
	} finally {
		nostrLoading = false;
	}
}

async function loginWithNsec() {
	// Re-entry guard: form's on:submit can fire via Enter or rapid double-
	// click before the disabled state on the button takes effect, which
	// would decode + sign the same nsec twice and double-fire the network
	// exchange.
	if (nsecLoading) return;
	if (!nsec.trim()) return;
	nsecLoading = true;
	let secretKey: Uint8Array | null = null;

	// Phase 1: decode + sign (sync, only fails on malformed key).
	let signed: VerifiedEvent;
	try {
		secretKey = decodeNsec(nsec);
		signed = signAuthWithSecretKey(secretKey);
		nsec = "";
	} catch {
		errToast($_("login.nsecInvalid"));
		console.error("Nsec decode failed");
		if (secretKey) secretKey.fill(0);
		nsecLoading = false;
		return;
	}

	// Phase 2: network exchange. Reuses the same 401-vs-generic classifier
	// so transport errors don't get mis-reported as "invalid nsec".
	try {
		await exchangeSignedEvent(signed);
	} catch (err) {
		const status = (err as { response?: { status?: number } })?.response
			?.status;
		errToast(status === 401 ? $_("login.nostrFailed") : $_("login.nostrError"));
		console.error("Nsec login failed:", status ?? "unknown");
	} finally {
		// Best-effort zeroing. V8 may have copies elsewhere, but this covers
		// the primary reference.
		if (secretKey) secretKey.fill(0);
		nsecLoading = false;
	}
}

$: anyLoading = nostrLoading || nsecLoading;
</script>

{#if hasNostrExtension}
	<button
		type="button"
		on:click={loginWithExtension}
		disabled={anyLoading}
		class="w-full rounded-lg bg-purple-600 px-4 py-2 font-semibold text-white transition-colors hover:bg-purple-700 disabled:opacity-50"
	>
		{nostrLoading ? $_("login.nostrSigning") : $_("login.nostrExtension")}
	</button>
{/if}

{#if showNsecInput}
	<form on:submit|preventDefault={loginWithNsec} class="space-y-2">
		<label
			for="nsec"
			class="block text-sm font-semibold text-primary dark:text-white"
		>
			{$_("login.nsecLabel")}
		</label>
		<input
			id="nsec"
			type="password"
			bind:value={nsec}
			placeholder="nsec1..."
			autocomplete="new-password"
			autocorrect="off"
			autocapitalize="off"
			spellcheck="false"
			class="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-mono text-sm text-primary dark:border-white/20 dark:bg-dark dark:text-white"
		/>
		<p class="text-xs text-body dark:text-white/50">
			{$_("login.nsecWarning")}
		</p>
		<button
			type="submit"
			disabled={nsecLoading || !nsec.trim()}
			class="w-full rounded-lg bg-purple-600 px-4 py-2 font-semibold text-white transition-colors hover:bg-purple-700 disabled:opacity-50"
		>
			{nsecLoading ? $_("login.nostrSigning") : $_("login.nsecSubmit")}
		</button>
	</form>
{:else}
	<button
		type="button"
		on:click={() => (showNsecInput = true)}
		class="w-full text-center text-sm text-link transition-colors hover:text-hover"
	>
		{$_("login.nsecToggle")}
	</button>
{/if}
