name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          needs-env: 'true'
          needs-sync: 'false'

      - name: Build app
        run: yarn run build
